<?php

namespace App\Domains\Users\Console;

use App\Domains\Users\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Hash;

class UserResetPassword extends Command
{
    protected $signature = 'user:reset-password {email} {--password= : Leave empty to auto-generate}';

    protected $description = 'Reset a user\'s password from the CLI.';

    public function handle(): int
    {
        $user = User::where('email', (string) $this->argument('email'))->first();
        if (! $user) {
            $this->error('No user with that email.');

            return self::FAILURE;
        }

        $provided = $this->option('password');
        $autoGenerated = $provided === null || $provided === '';
        $password = $autoGenerated ? bin2hex(random_bytes(16)) : (string) $provided;

        $user->forceFill([
            'password' => Hash::make($password),
            // Invalidate every authenticated surface — the point of an
            // admin-initiated reset is that old credentials may be compromised.
            'remember_token' => null,
        ])->save();
        $user->tokens()->delete();

        $this->info("Password reset for {$user->email}. Existing sessions and API tokens were revoked.");
        if ($autoGenerated) {
            $this->warn("Temporary password: {$password}");
        }

        return self::SUCCESS;
    }
}
